on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '17'
        cache: 'gradle'
    - name: Run tests
      run: ./gradlew test